services:
  # Backend Service
  - type: web
    name: mern-social-media-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        sync: false
      - key: PORT
        value: 3001

  # Frontend Service
  - type: static
    name: mern-social-media-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mern-social-media-api.onrender.com
